### ISSUE TITLE
[Bug] data-extension-installed

### ISSUE THREAD

**Issue by JuanPabloDiaz** [JuanPabloDiaz/chart.js#1]
![image](https://github.com/JuanPabloDiaz/chart.js/assets/25883220/298d318f-1504-4089-9019-0b7f622e6c00)

This warning is coming from React. It's saying that there are extra attributes on a server-rendered React element that were not expected. In this case, the attribute is data-extension-installed.

This can happen when the server and client render different content. React expects that the rendered content is the same between the server and the client. This is a key aspect of how server-side rendering (SSR) works in React.

To fix this issue, you need to ensure that the server and client render the same content. In this case, you need to make sure that the data-extension-installed attribute is added on both the server and the client, or not added at all.

**Comment by cpwallah** [comment]
hi i would like to work on this issue @JuanPabloDiaz

**Comment by JuanPabloDiaz** [comment]
go for it @cpwallah

**Comment by cpwallah** [comment]
@JuanPabloDiaz hi  brother i have git clone your project and install dependecies inside the file chart.js and it is working fine .if this is the only thing i have to do then can i make PR

**Comment by JuanPabloDiaz** [comment]
What is the cause of the error?

**Comment by cpwallah** [comment]
@JuanPabloDiaz  i mean everything is working fine

**Comment by cpwallah** [comment]
@JuanPabloDiaz  so what you want from me i did not undestand ?
